//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotGLib.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GotGLib.Res.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliance score and cities.
        /// </summary>
        public static string AlianceScoreAndCities {
            get {
                return ResourceManager.GetString("AlianceScoreAndCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        public static string Alliance {
            get {
                return ResourceManager.GetString("Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacking city.
        /// </summary>
        public static string AttackCity {
            get {
                return ResourceManager.GetString("AttackCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg def. rep. gain.
        /// </summary>
        public static string AvgDefRepGain {
            get {
                return ResourceManager.GetString("AvgDefRepGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg k. units gain.
        /// </summary>
        public static string AvgKilledUnitsGain {
            get {
                return ResourceManager.GetString("AvgKilledUnitsGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg off. rep. gain.
        /// </summary>
        public static string AvgOffRepGain {
            get {
                return ResourceManager.GetString("AvgOffRepGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg score gain.
        /// </summary>
        public static string AvgScoreGain {
            get {
                return ResourceManager.GetString("AvgScoreGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry capacity %.
        /// </summary>
        public static string CarryCapacityPerc {
            get {
                return ResourceManager.GetString("CarryCapacityPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavern coords.
        /// </summary>
        public static string CavernCoords {
            get {
                return ResourceManager.GetString("CavernCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caverns.
        /// </summary>
        public static string Caverns {
            get {
                return ResourceManager.GetString("Caverns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caverns rank.
        /// </summary>
        public static string CavernsRank {
            get {
                return ResourceManager.GetString("CavernsRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavern type.
        /// </summary>
        public static string CavernType {
            get {
                return ResourceManager.GetString("CavernType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities +/-.
        /// </summary>
        public static string Cities_pm {
            get {
                return ResourceManager.GetString("Cities_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        public static string Continent {
            get {
                return ResourceManager.GetString("Continent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continents.
        /// </summary>
        public static string Continents {
            get {
                return ResourceManager.GetString("Continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deffense rep. rank.
        /// </summary>
        public static string DefRepRank {
            get {
                return ResourceManager.GetString("DefRepRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense reputation.
        /// </summary>
        public static string DefReputation {
            get {
                return ResourceManager.GetString("DefReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (difference).
        /// </summary>
        public static string Difference1 {
            get {
                return ResourceManager.GetString("Difference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential score.
        /// </summary>
        public static string DiffScore {
            get {
                return ResourceManager.GetString("DiffScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire stats.
        /// </summary>
        public static string EmpireStats {
            get {
                return ResourceManager.GetString("EmpireStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuffucient capacity.
        /// </summary>
        public static string InsufficientCapacity {
            get {
                return ResourceManager.GetString("InsufficientCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New?.
        /// </summary>
        public static string IsNew {
            get {
                return ResourceManager.GetString("IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed units.
        /// </summary>
        public static string KilledUnits {
            get {
                return ResourceManager.GetString("KilledUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K. units rank.
        /// </summary>
        public static string KilledUnitsRank {
            get {
                return ResourceManager.GetString("KilledUnitsRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New only.
        /// </summary>
        public static string NewOnly {
            get {
                return ResourceManager.GetString("NewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense rep. rank.
        /// </summary>
        public static string OffRepRank {
            get {
                return ResourceManager.GetString("OffRepRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense reputation.
        /// </summary>
        public static string OffReputation {
            get {
                return ResourceManager.GetString("OffReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page loading... please be patient :).
        /// </summary>
        public static string PageLoading {
            get {
                return ResourceManager.GetString("PageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress %.
        /// </summary>
        public static string ProgressPerc {
            get {
                return ResourceManager.GetString("ProgressPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids reports.
        /// </summary>
        public static string RaidReports {
            get {
                return ResourceManager.GetString("RaidReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank +/-.
        /// </summary>
        public static string Rank_pm {
            get {
                return ResourceManager.GetString("Rank_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        public static string Rankings {
            get {
                return ResourceManager.GetString("Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh plot.
        /// </summary>
        public static string RefreshPlot {
            get {
                return ResourceManager.GetString("RefreshPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report date.
        /// </summary>
        public static string ReportDT {
            get {
                return ResourceManager.GetString("ReportDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        public static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score +/-.
        /// </summary>
        public static string Score_pm {
            get {
                return ResourceManager.GetString("Score_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (Score points/minute).
        /// </summary>
        public static string ScoreSpeed {
            get {
                return ResourceManager.GetString("ScoreSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected report.
        /// </summary>
        public static string SelectedReport {
            get {
                return ResourceManager.GetString("SelectedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot (timeline).
        /// </summary>
        public static string TimePlot {
            get {
                return ResourceManager.GetString("TimePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World - aliance score.
        /// </summary>
        public static string WorldAlianceScore {
            get {
                return ResourceManager.GetString("WorldAlianceScore", resourceCulture);
            }
        }
    }
}
