//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotGLib.JS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GotGLib.JS.JSRes", typeof(JSRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function InitAjaxHandlers(t)
        ///{
        ///
        ///    //lista raportów z raidów
        ///    /*
        ///    $.post(&quot;overview/rreps.php&quot;, function (data)
        ///    {
        ///        alert(&apos;res...&apos;);
        ///        hobbita.ajax_success(&quot;rreps.php&quot;, data);
        ///    });
        ///    */
        ///
        ///    $.post(&quot;overview/gFrep.php&quot;, &quot;a=6543691871&quot;, function (data) {
        ///        alert(&apos;res...&apos;);
        ///        hobbita.ajax_success(&quot;gFrep.php&quot;, data);
        ///    });
        ///
        ///    /*
        ///    var jqxhr = $.post(&quot;rreps.php&quot;, function () {
        ///        alert(&quot;success&quot;);
        ///    })
        ///      .done(function () {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AJAX {
            get {
                return ResourceManager.GetString("AJAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function CotGBrowser_RegisterChatListeners(t)
        ///{
        ///    //t - musi byc jakis argument
        ///    $(&apos;#chatDisplay&apos;).bind(&apos;DOMNodeInserted&apos;, function (e) {
        ///        hobbita.world_chat_message(e.target.innerText, e.target.innerHTML);
        ///    });
        ///}
        ///.
        /// </summary>
        internal static string ChatListener {
            get {
                return ResourceManager.GetString("ChatListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function CotGBrowser_GetRanks(aType, aContinent) {
        ///    //wyciągam sobie bazowy adres
        ///    var _baseURL = document.URL.split(&quot;World00.php&quot;)[0];
        ///
        ///    var callback = function (dataReceived) {
        ///        hobbita.rankings(dataReceived, aType, aContinent);
        ///    };
        ///
        ///    var failCallback = function (jqXHR, textStatus) {
        ///        hobbita.failed(textStatus, aType, aContinent);
        ///    };
        ///
        ///    //a=0 - punktacja graczy na kont
        ///    //a=1 - punktacja sojuszy na kont
        ///    //a=5 - units kills (total)
        ///    //a=4 - def  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetRanks {
            get {
                return ResourceManager.GetString("GetRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function CotGBrowser_RefreshRaidReports(t) {
        ///    //lista raportów z raidów
        ///
        ///    $.post(&quot;overview/rreps.php&quot;, function (data)
        ///    {
        ///        hobbita.raids_repors(data);
        ///    });
        ///}
        ///
        ///function CotGBrowser_GetRaidReport(reportId) {
        ///    //kokretny raport z raidu
        ///
        ///    $.post(&quot;overview/gFrep.php&quot;, &quot;a=&quot; + reportId, function (data)
        ///    {
        ///        hobbita.raid_report(data);
        ///    });
        ///}
        ///
        ///function CotGBrowser_RefreshTroopsOverview(t) {
        ///    $.post(&quot;overview/trpover.php&quot;, function (data) {
        ///        hobbita.t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Overviews {
            get {
                return ResourceManager.GetString("Overviews", resourceCulture);
            }
        }
    }
}
